In [1]:
import numpy as np

In [4]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

### Array/Vector Indexing and Slicing

In [12]:
arr[2:5]

array([13, 14, 15])

In [14]:
arr[1:9:2]

array([12, 14, 16, 18])

### Numpy Indexing and Slicing of Matrix

In [26]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [28]:
arr[3,4]
#[row_index,col_index]

np.int64(20)

In [29]:
slice=arr[0:2,1:4]
slice

array([[2, 3, 4],
       [7, 8, 9]])

In [ ]:
slice_block=arr[3:,3:]
slice_block

array([[19, 20],
       [24, 25],
       [29, 30]])

In [37]:
slice_row=arr[1]
slice_row

array([ 6,  7,  8,  9, 10])

In [39]:
slice_column=arr[:,1]
slice_column

array([ 2,  7, 12, 17, 22, 27])

### Boolean Indexing

In [52]:
arra=np.arange(11,21)
arra

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [53]:
bool_index=arra%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [54]:
arra=arra[bool_index]
arra

array([12, 14, 16, 18, 20])