In [1]:
import numpy as np

### Array Operations

#### Arithmatic Operation

In [9]:
array1=np.arange(1,6)
#([1,2,3,4,5])
array2=np.arange(6,11)
#([6,7,8,9,10])
array2

array([ 6,  7,  8,  9, 10])

In [11]:
Array_sum= array1+array2
Array_sum

array([ 7,  9, 11, 13, 15])

In [12]:
Array_product=array1*array2
Array_product

array([ 6, 14, 24, 36, 50])

In [13]:
floor_div=array1//array2
floor_div

array([0, 0, 0, 0, 0])

In [15]:
power=array1**array2
power

array([      1,     128,    6561,  262144, 9765625])

#### Brodacasting

Broadcasting is one of the most powerful features in NumPy. It allows you to perform arithmetic operations (like addition or multiplication) on arrays of different shapes without having to manually duplicate data to make the sizes match

In [18]:
#[10,20,30,40,50]
array_brodcasting=np.arange(10,51,10)
array_brodcasting

array([10, 20, 30, 40, 50])

In [19]:
array_brodcasting+10

array([20, 30, 40, 50, 60])

In [22]:
l=[10,20,30,40]
list_arr=np.array(l)
list_arr

array([10, 20, 30, 40])

In [23]:
list_arr+10

array([20, 30, 40, 50])

#### Deep and Shallow copy

In [30]:
array_org=np.arange(1,21)
array_org

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [34]:
array_org[:5]*10
#shallow copy does not change original array

array([10, 20, 30, 40, 50])

In [35]:
array_org

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
array_copy=array_org
array_copy[0]=99
array_copy
#deep copy i.e original array changed 
#both point to same memory location so change by one affect other meanwhile in shallow it point to completely different memory locations

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [37]:
array_org

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

#### Matrix Operation

In [39]:
array_A=np.arange(1,5).reshape(2,2)
array_B=np.arange(5,9).reshape(2,2)

In [40]:
array_A

array([[1, 2],
       [3, 4]])

In [41]:
array_B

array([[5, 6],
       [7, 8]])

In [ ]:
array_A @ array_B
#array multiplication 

array([[19, 22],
       [43, 50]])

In [43]:
np.dot(array_A,array_B)

array([[19, 22],
       [43, 50]])

In [44]:
array_A

array([[1, 2],
       [3, 4]])

In [ ]:
array_A.T
#Matrix Transpose

array([[1, 3],
       [2, 4]])

### Advance Array Manipulation

#### Stacking Array

In [48]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])

In [49]:
np.hstack((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [51]:
np.column_stack((a,b))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [52]:
np.row_stack((a,b))

C:\Users\Mayur\AppData\Local\Temp\ipykernel_15664\1307586492.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a,b))


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

#### Splitting Array

In [54]:
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.split(c,2,1)
#split (array_name,divide_in_parts,axis)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [60]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [62]:
split_array=np.vsplit(c,2)
split_array

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [63]:
for i in split_array:
    print(i)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
