In [1]:
import numpy as np

### 1. Basic Array Creation

In [2]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [6]:
arra=[1,2,3.5]
arra

[1, 2, 3.5]

In [7]:
np.array(arra)

array([1. , 2. , 3.5])

In [10]:
l=[[1,2,3,4],[5,6,7,8],[9,20,11,12]]
l

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 20, 11, 12]]

In [11]:
np.array(l)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 20, 11, 12]])

### 2. Array Generation function

In [22]:
arr=np.arange(1,10)
arr



array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
array1=np.arange(1,12,2)
array1

array([ 1,  3,  5,  7,  9, 11])

In [26]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

### 3. Random Generation function

In [39]:
np.random.rand(5)
#normalization (values from 0-1)

array([0.29834523, 0.69683987, 0.08421443, 0.77774301, 0.85555753])

In [ ]:
np.random.randn(10)
#standardizaton(values from -3 to 3)

array([-0.02030874, -0.82541456, -0.76513942,  0.18797375,  1.4713125 ,
        1.57356876,  1.42430611,  0.93266384,  2.32215078, -0.70265771])

In [52]:
np.random.randint(10,20,10)
#random 5 values from int  10-20 

array([11, 12, 16, 19, 10, 15, 10, 18, 14, 11], dtype=int32)

### Array Attributes

In [57]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.shape #-->(3,3)
# arr.size --> 9

(3, 3)

In [63]:
arr.dtype

dtype('int64')

### Array Methods

In [64]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
arr.min()

np.int64(1)

In [66]:
arr.max()

np.int64(9)

In [ ]:
np.random.choice(arr.flatten())
#converted 3-D to 1-D and then choose random value among them

np.int64(9)

In [71]:
arr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
arr.sum()

np.int64(45)

In [ ]:
np.sum(arr, axis=0)
#axis =0 i.e sum of all column values
# axis=1 i.e. sum of all row values

array([12, 15, 18])

In [74]:
np.sum(arr,1)

array([ 6, 15, 24])

In [75]:
arr.mean()

np.float64(5.0)

In [ ]:
arr.std()
#standard deviation

np.float64(2.581988897471611)

In [88]:
arr.argmax()
#give index of max value 
# if axis not mentioned flattens the array
#if axis 0 columns max value index
#if axis 1 rows max value index

np.int64(8)

In [81]:
arr.argmin()

np.int64(0)

### Reshaping and Resizing

In [92]:
arra=np.arange(1,31)
arra

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [93]:
arra.reshape(5,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [ ]:
np.resize(arr,(3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [103]:
new_array=[]
np.resize(new_array,(2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])