In [1]:
import numpy as np

### 1. Basic Array Creation

In [2]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [6]:
arra=[1,2,3.5]
arra

[1, 2, 3.5]

In [7]:
np.array(arra)

array([1. , 2. , 3.5])

In [10]:
l=[[1,2,3,4],[5,6,7,8],[9,20,11,12]]
l

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 20, 11, 12]]

In [11]:
np.array(l)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 20, 11, 12]])

### 2. Array Generation function

In [22]:
arr=np.arange(1,10)
arr



array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
array1=np.arange(1,12,2)
array1

array([ 1,  3,  5,  7,  9, 11])

In [26]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

### 3. Random Generation function

### Array Attributes

### Array Methods

### Reshaping and Resizing